@ApiServer_HostAddress = https://localhost:44321

GET {{ApiServer_HostAddress}}/weatherforecast/
Accept: application/json

###



GET {{ApiServer_HostAddress}}/api/Database/
###


POST {{ApiServer_HostAddress}}/api/Database/
###


POST http://localhost:8080/Api/Database/
###

GET https://localhost:44321/weatherforecast/
###

GET https://localhost:44321/SaveWeatherForecast/
###



POST {{ApiServer_HostAddress}}/WeatherForecast/save
Content-Type: application/json

{
  "date": "2025-10-20",
  "temperatureC": 23,
  "summary": "Warm"
}
###

GET {{ApiServer_HostAddress}}/api/User/test
###


POST {{ApiServer_HostAddress}}/api/User/login
Content-Type: application/json
Accept: application/json

{ "username": "testuser", "password": "testpassword" }
###


POST {{ApiServer_HostAddress}}/api/User/register
Content-Type: application/json
Accept: application/json

{
  "username": "testuser",
  "password": "testpassword",
  "email": "test@example.com",
  "phoneNumber": "1234567890"
}
###
