# @ApiServer_HostAddress = http://localhost:5131
@ApiServer_HostAddress = https://localhost:44322

GET {{ApiServer_HostAddress}}/api/User/test
###


POST {{ApiServer_HostAddress}}/api/User/login
Content-Type: application/json
Accept: application/json

{ "username": "testuser", "password": "testpassword" }
###


POST {{ApiServer_HostAddress}}/api/User/register
Content-Type: application/json
Accept: application/json

{
  "username": "testuser",
  "password": "testpassword",
  "email": "test@example.com",
  "phoneNumber": "1234567890"
}
###
