# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./ApiServer.sln --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal    

  build-container:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build -t myapp:latest -f ApiServer/Dockerfile ApiServer/
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PAT }}
    - name: Tag Docker image for GitHub Container Registry
      run: |
        REPO_LC=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        IMAGE_ID=ghcr.io/${REPO_LC}/myapp:latest
        docker tag myapp:latest $IMAGE_ID
    - name: Push Docker image to GitHub Container Registry
      run: |
        REPO_LC=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        IMAGE_ID=ghcr.io/${REPO_LC}/myapp:latest
        docker push $IMAGE_ID
